name: run_tests.yml
on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10 # My current version
        uses: actions/setup-python@v5
        with:
          python-version: "3.10.4"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python scripts/run_tests.py
